### ISSUE TITLE
colors general css

### ISSUE THREAD

**Issue by BlinkingHeimdall** [BlinkingHeimdall/show-pro#2]

**Comment by Draxion2** [comment]
Colors: #FF8822, #eee, #000
Possible colors that go well with green: orange, yellow, violet, tangerine

**Comment by Draxion2** [comment]
How about these for the colors?

`:root {
    --primary: #1DB954;
    --secondary: #a6eca8;
    --tertiary: #d2fdbb;
    --black: #000;
    --white: #fff;
    --border-primary: #c0c0c0;
    --border-secondary: #98985b;
}`

**Comment by Draxion2** [comment]
Issue solved
