### ISSUE TITLE
Larger Screen Sizes and Centering

### ISSUE THREAD

**Issue by benny623** [BlinkingHeimdall/show-pro#28]
- Fix the green background on larger screen sizes
- Center the content on the page

**Comment by Draxion2** [comment]
**Solution**

`body {
    background-color: var(--primary);
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    height: 100%;
    position: absolute;
    overflow: hidden;
}

#main-page {
    height: 100%;
    margin: 0 auto;
}`
